### ISSUE TITLE
比对窗口中查询条件带出国药准字/注册证号，并查询出结果

### ISSUE THREAD

**Issue by immo-kirito** [Immortalshealth/HPMS3.0#103]

**Comment by NSBen** [comment]
@immo-duanzhao  这个你跳转的时候要加上pzwh这个字段
![image](https://user-images.githubusercontent.com/7847172/34925035-cb4148cc-f9e1-11e7-8065-f5be577ffabf.png)

**Comment by immo-wsn** [comment]
提交到svn了
