### ISSUE TITLE
导入数据后,出现角色数据错误

### ISSUE THREAD

**Issue by immo-leeyouzhi** [Immortalshealth/HPMS3.0#107]
![1](https://user-images.githubusercontent.com/34183102/34506596-45e3f46c-f069-11e7-8af9-eb4f39092951.png)

**Comment by immo-hyb** [comment]
处理方法已经跟唐顺兰说了。
@immo-tang  如果你处理完后没问题了 请关闭

**Comment by immo-wsn** [comment]
唐老师自己已经处理了;因为角色表缺少了临床医生这条记录，所以页面展示为undefined，在角色表把临床医生这条记录插进去就可以了;
