### ISSUE TITLE
新版药品目录测试－规格、规格属性有误

### ISSUE THREAD

**Issue by immo-sitingchen** [Immortalshealth/HPMS3.0#11]
建议：不需要单独显示“规格属性”这个字段，因为“规格”已经合并了规格属性。另外：当“规格属性=无”的时候，“规格”字段不要显示“(无)”，避免不必要的误会。

![image](https://user-images.githubusercontent.com/33406481/32430209-e7207d0e-c293-11e7-80f7-6f4a02931533.png)

**Comment by immo-joyce** [comment]
当“规格属性=无”的时候，“规格”字段不要显示“(无)”，避免不必要的误会。

**Comment by immo-hyb** [comment]
已经修复
