### ISSUE TITLE
住院点评查看明细报错

### ISSUE THREAD

**Issue by immo-leeyouzhi** [Immortalshealth/HPMS3.0#110]
![qq 20180103094845](https://user-images.githubusercontent.com/34183102/34506895-aa304d38-f06b-11e7-97cd-da662e6baf67.jpg)

**Comment by immo-leeyouzhi** [comment]
住院点评后台报错
![5](https://user-images.githubusercontent.com/34183102/34506923-f8b720e4-f06b-11e7-87b2-944c41fa90f9.png)

**Comment by immo-leeyouzhi** [comment]
住院点评出问题定位：eng_order_drug  给药途径的数据有问题

**Comment by immo-leeyouzhi** [comment]
住院点评出问题定位：eng_order_drug  给药途径的数据有问题

**Comment by immo-tang** [comment]
去药剂科问了　又在数据库中查了导过来的业务表数据,只是admin_route有这个$”字符,　要不先处理这个吧,以后发现在再处理
