### ISSUE TITLE
药品目录页面部分药品出现以下数据列显示

### ISSUE THREAD

**Issue by immo-leeyouzhi** [Immortalshealth/HPMS3.0#112]
![7](https://user-images.githubusercontent.com/34183102/34506960-78a1e6ea-f06c-11e7-9a97-b0992f759220.png)

**Comment by immo-hyb** [comment]
@immo-kirito @immo-leeyouzhi 这个有相关的数据环境吗？目前不知道如何重现这个问题

**Comment by immo-hyb** [comment]
这个问题之前应该是数据问题，目前在连山医院的界面未发现。
@immo-tang 如果没问题了请关闭
