### ISSUE TITLE
组号为0，注射剂配伍禁忌不生效

### ISSUE THREAD

**Issue by immo-linziying** [Immortalshealth/HPMS3.0#118]
广医三院中，注射剂组号为0时，配伍规则以及配伍禁忌表均不生效。

![1](https://user-images.githubusercontent.com/34183265/34602263-18915680-f23a-11e7-811a-a5f76416947d.png)
![2](https://user-images.githubusercontent.com/34183265/34602264-18c90648-f23a-11e7-972b-204ab041fa56.png)

**Comment by immo-xxl** [comment]
已经解决
