### ISSUE TITLE
中药饮片规则来源更改

### ISSUE THREAD

**Issue by immo-linziying** [Immortalshealth/HPMS3.0#119]
目前最新的药典为2015年版，但中药饮片的规则来源为2010年版药典。
请将标准库中“中华人民共和国药典2010年版第一部”的来源，批量更改为“中华人民共和国药典2015年版第一部”。
更改完成后，请通知项目组，并提供更新方法，以便更新到医院。

![qq 20180109105417](https://user-images.githubusercontent.com/34183265/34702969-82426c88-f52b-11e7-818c-1a68601ab3ec.png)

**Comment by immo-leeyouzhi** [comment]
#545条
select * from drug where draw like '%中华人民共和国药典2010年版第一部%';


#更新步骤1：替换文本
update drug  set draw  = replace(draw,'中华人民共和国药典2010年版第一部','中华人民共和国药典2015年版第一部') where draw LIKE '%中华人民共和国药典2010年版第一部%';

#更新步骤2：重新编译所有药品规则

**Comment by immo-xxl** [comment]
已处理
