### ISSUE TITLE
新知识库维护问题

### ISSUE THREAD

**Issue by immo-eugene** [Immortalshealth/HPMS3.0#120]
1、某些文章排版有问题，如：抗菌药物临床应用指导原则 （2015 年版）
（1）右方版面为空
![tim 20180111100036 1](https://user-images.githubusercontent.com/33345142/34807068-7dc1e338-f67e-11e7-9ab2-fde50f104eeb.jpg)

（2）表格显示格式有误
![tim 20180111110218](https://user-images.githubusercontent.com/33345142/34807106-cc619588-f67e-11e7-90dd-f3b16edde3ed.jpg)
![tim 20180111110233](https://user-images.githubusercontent.com/33345142/34807132-f57c4620-f67e-11e7-9d1f-6af499db486c.jpg)

2、在“”计算公式及检验结果“栏目，检验结果的左侧目录分类不相符
如：急性胰腺炎实际属于第二类——消化系统疾病，但左侧目录列入第三类——心血管系统疾病
![tim 20180111105531](https://user-images.githubusercontent.com/33345142/34807266-ac3e5bc8-f67f-11e7-91c8-2ba5d378f76c.jpg)

**Comment by immo-wsn** [comment]
这些应该都是导入的时候有问题     程序应该是没问题的
