### ISSUE TITLE
住院医嘱查询页面打开卡死与等待几分钟

### ISSUE THREAD

**Issue by imm-mobocheng** [Immortalshealth/HPMS3.0#124]
卡死：
![image](https://user-images.githubusercontent.com/34183070/35026123-1127b3a0-fb84-11e7-9393-d6505c643f82.png)

等几分钟药品没出来：
![image](https://user-images.githubusercontent.com/34183070/35026230-b0230072-fb84-11e7-8d7e-ca76c9a5415a.png)

**Comment by imm-mobocheng** [comment]
各位，此问题普遍存在。请问进展情况如何。

**Comment by immo-kirito** [comment]
@immo-wsn    小伍看下什么问题

**Comment by imm-mobocheng** [comment]
@immo-hyb 你提供的更新，测试速度可以。非常棒！

**Comment by imm-mobocheng** [comment]
各位，此问题可以close了。
