### ISSUE TITLE
广药附三规则单次剂量单位在数据库中手工增加了u单位，药品规则单次剂量u单位不生效

### ISSUE THREAD

**Issue by immo-fangjun** [Immortalshealth/HPMS3.0#129]
广药附三规则单次剂量单位在数据库中手工增加了u单位，药品规则单次剂量u单位不生效 ，重新编译药品规则和重启Tomcat后，用测试工具测试始终不生效
![default](https://user-images.githubusercontent.com/34183091/35076194-0f2f2e80-fc32-11e7-9bff-7528f080463e.png)

**Comment by immo-lindanxia** [comment]
某些药物生物效能的最小效价单元就叫"单位"(u);经由国际协商规定出的标准单位，称为"国际单位"(IU)。我们规则库中统一使用的是国际单位（iu），两者的关系为1u=1iu。建议在同义词比对-“重量单位”中增加iu的比对关系，若在规则中增加u会造成单位不统一。

**Comment by immo-wsn** [comment]
已经修复了
