### ISSUE TITLE
新版药品目录测试－下载目录药品类型有误

### ISSUE THREAD

**Issue by immo-sitingchen** [Immortalshealth/HPMS3.0#13]
下载目录药品类型有误

![image](https://user-images.githubusercontent.com/33406481/32471861-15d76a4a-c325-11e7-848c-3c4dbfb87600.png)

![image](https://user-images.githubusercontent.com/33406481/32471958-9e097b56-c325-11e7-8825-decc06e865b3.png)

**Comment by immo-hyb** [comment]
已修改
