### ISSUE TITLE
东莞五院药品说明书调用错误

### ISSUE THREAD

**Issue by immo-linziying** [Immortalshealth/HPMS3.0#130]
药品解毒生肌膏10G，在标准库中并无说明书及规则。医院药品比对正确，但调用了西洋参颗粒的说明书。
MCD中的编码：
西洋参颗粒：Y1441-A1-6
解毒生肌膏：Z061701-180101-A391-01-0000012
医院截图如下
![1](https://user-images.githubusercontent.com/34183265/35087601-c1add9a6-fc6b-11e7-9118-d875fbcd0c9b.png)
![2](https://user-images.githubusercontent.com/34183265/35087609-c89c2240-fc6b-11e7-991f-edb081b12306.png)

**Comment by immo-jianyu** [comment]
此问题是调用bug，没有说明书的都调出了西洋参，已经提出修改，暂时关闭
