### ISSUE TITLE
肇庆二院说明书(7份说明书)

### ISSUE THREAD

**Issue by immo-tang** [Immortalshealth/HPMS3.0#133]
1.小牛血清去蛋白注射　　说明书更新　正常(截止1月21)
2.注射用艾司奥美拉唑钠　说明书更新　正常(截止1月21)
3.(自)碳酸司维拉姆片(J)　 说明书更新　正常(截止1月24)
4.小儿豉翘清热颗粒　　　　比对完成　正常(截止1月23)
5.(乙)小儿金翘颗粒　　　医院已提供说明书  (截止2月4日更新完成)
6.(自)蒲地蓝消炎口服液　　比对完成　　正常(截止1月23)
7.(自)盐酸西替利嗪滴剂　医院已提供说明书 (截止2月4日更新完成)

**Comment by immo-kirito** [comment]
@immo-tang   请描述不正常的情况是什么，说明问题不要只是说一个不正常

**Comment by immo-tang** [comment]
3.(自)碳酸司维拉姆片(J)　 说明书更新　不正常

![image](https://user-images.githubusercontent.com/34183062/35200991-c5bf711a-ff51-11e7-8a78-382e186788ef.png)

**Comment by immo-jianyu** [comment]
肇庆市二新增说明书
**盐酸西替利嗪滴剂
小儿金翘颗粒**
曲司氯铵胶囊
地氯雷他定糖浆
小儿氨酚黄那敏颗粒
已录入，更新文档1.26已发大明《肇庆市二、广药附三、莞五、茶山1月新增-发大明》

**Comment by immo-xxl** [comment]
已解决，测试没有问题
