### ISSUE TITLE
解毒生肌膏说明书调用有问题

### ISSUE THREAD

**Issue by imm-mobocheng** [Immortalshealth/HPMS3.0#141]
调用出来的说明书不对应：
![image](https://user-images.githubusercontent.com/34183070/35215387-0832211c-ff9f-11e7-9f87-2491b9d31ae6.png)

比对到10G规格，如下：
![image](https://user-images.githubusercontent.com/34183070/35215375-01b023de-ff9f-11e7-8abb-d09a2769c292.png)

**Comment by immo-jianyu** [comment]
说明书库没有解毒生肌膏的说明书，调用逻辑也有误，调不出说明书的都调出了西洋参颗粒
解决小莫的问题第一个要你回传说明书录入，第二步是技术解决调不出相关说明书也不要乱显示这个bug。
我先关闭这个问题，另外提出修改这个bug的需求。
