### ISSUE TITLE
说明书调用bug（没有相关的都显示西洋参颗粒）

### ISSUE THREAD

**Issue by immo-jianyu** [Immortalshealth/HPMS3.0#143]
![35215387-0832211c-ff9f-11e7-9f87-2491b9d31ae6](https://user-images.githubusercontent.com/34562067/35262373-4f3d849c-004f-11e8-9a91-feaef71522e1.png)
来源于肇庆二院调用 解毒生肌膏（广西），说明书库无此说明书，无比对错误，理应调不出任何说明书，但显示了西洋参颗粒。

**Comment by immo-linziying** [comment]
这个是东莞五院的问题

**Comment by immo-jianyu** [comment]
调用错误是因为该药无副类名称，副类名称已由丹霞重新维护
