### ISSUE TITLE
肇庆市一前置审方：审方通知形式修改。

### ISSUE THREAD

**Issue by immo-tanxu** [Immortalshealth/HPMS3.0#155]
目前医院的审方提示是通过右下角弹框的形式进行通知，而且会一直推送，电脑右侧会全部被覆盖，同时覆盖了审方界面系统审核结果一列，药师需要逐条关闭审方通知。
       将审方通知修改成状态栏浏览器图标闪烁，浏览器页面标签闪烁。

**Comment by immo-xxl** [comment]
@immo-tanxu   这个问题公司本地的服务器以及修改
