### ISSUE TITLE
广药附三 带*号的医院药品规则不生效

### ISSUE THREAD

**Issue by immo-linziying** [Immortalshealth/HPMS3.0#157]
![default](https://user-images.githubusercontent.com/34183265/36624091-07372706-1946-11e8-9528-91815a4b55e2.png)
广药附三多次发现个别现带*号的药品，在评估页面测试规则不生效的情况。之前处理后，依然会发现有其他药品存在这个问题，院方希望能彻底解决此问题。

**Comment by cashely** [comment]
@immo-linziying   带星号的都是医院的药品吗，有没有药品目录比对

**Comment by immo-kirito** [comment]
@immo-linziying  带星号的都是医院的药品吗，有没有药品目录比对

**Comment by immo-linziying** [comment]
@immo-kirito 药品已经比对过了，也把标准库的规则复制到自定义层，但规则依然不生效。

**Comment by immo-hyb** [comment]
确实奇怪，老是有的药品规则不生效。。上次换了下跑引擎的代码就可以了。目前还是没找到问题根源。
子莹，你把远程给下我

**Comment by immo-hyb** [comment]
重启下服务，这个药品的规则可以生效了~  具体之前这个药品规则不生效的原因没查到。
