### ISSUE TITLE
新版药品目录测试-停用的数据不要算入未比对

### ISSUE THREAD

**Issue by immo-sitingchen** [Immortalshealth/HPMS3.0#16]
停用的数据不要算入未比对

![image](https://user-images.githubusercontent.com/33406481/32472577-e66ef17a-c328-11e7-84ca-33ad4e1709b8.png)

**Comment by immo-hyb** [comment]
请业务评估   斯婷的逻辑是否正确，如果需要这样做，我们再来修改

**Comment by immo-xxl** [comment]
已解决
