### ISSUE TITLE
患者信息和患者列表显示权限分配

### ISSUE THREAD

**Issue by immo-leung** [Immortalshealth/HPMS3.0#164]
![21](https://user-images.githubusercontent.com/34183140/37273440-cfbdd852-2614-11e8-8cb0-f55e12058781.jpg)
![22](https://user-images.githubusercontent.com/34183140/37273441-cfec28ec-2614-11e8-9b0b-229d6d039428.jpg)
根据用户角色（机构管理员）权限增加患者列表和患者信息显示内容，省级显示全省患者信息、市级显示全市患者信息、区级显示区级患者信息，只提供查看功能，不提供修改的功能。

**Comment by immo-kirito** [comment]
对应项目的需求请提到对应的项目
