### ISSUE TITLE
发药登记修改单位转换功能

### ISSUE THREAD

**Issue by immo-leung** [Immortalshealth/HPMS3.0#166]
![24](https://user-images.githubusercontent.com/34183140/37318656-a8160ee0-26a6-11e8-8e8d-b95c77f7791b.jpg)
在发药登记中，发药单需添加药品单位并添加药品单位数量转换功能，同步修改发药单API接口以及与众天对接接口。

**Comment by immo-kirito** [comment]
对应项目的需求请提到对应的项目
