### ISSUE TITLE
规则管理器维护

### ISSUE THREAD

**Issue by immo-eugene** [Immortalshealth/HPMS3.0#170]
规则管理器调取说明书的页面中，说明书左侧添加目录栏后，导致有少部分新说明书的首字段显示不全，需要技术协助调整版面
![tim 20180226112821](https://user-images.githubusercontent.com/33345142/37387697-74014f3c-2798-11e8-9846-02fa4875f263.jpg)
另外，版面需要设置自动换行功能
![tim 20180314150645](https://user-images.githubusercontent.com/33345142/37388140-420db59a-279a-11e8-85e7-d0d347a49936.jpg)

**Comment by immo-wsn** [comment]
不会换行是因为说明书上面有一个行有很多空格,把整份文档的宽度都撑宽了.. 只能改那份说明书的格式;
![image](https://user-images.githubusercontent.com/35050720/37633520-aab411f6-2c2d-11e8-9c77-251954bc64c7.png)
遮挡的那个改了样式,看下还有没有问题
