### ISSUE TITLE
知识库文献需按发布时间倒序排列

### ISSUE THREAD

**Issue by immo-jianyu** [Immortalshealth/HPMS3.0#172]
知识库内容，现按照点击率排序，不合理。
[改动为：按照发布时间倒序排列，以直观显示最新的政策]
![qq 20180316115015](https://user-images.githubusercontent.com/34562067/37503101-698960d8-2911-11e8-9d5c-d33131aafd82.jpg)

![1](https://user-images.githubusercontent.com/34562067/37692245-6260fb60-2cf2-11e8-8bf3-43d820aed72d.jpg)
![2](https://user-images.githubusercontent.com/34562067/37692246-62d41b4a-2cf2-11e8-8e4d-799856cb1d92.jpg)
![3](https://user-images.githubusercontent.com/34562067/37692248-64d88048-2cf2-11e8-806e-8f1212701ab8.jpg)

**Comment by immo-LinhaiTan** [comment]
已完成

**Comment by immo-jianyu** [comment]
时间倒序完成，但由于时间格式不一，导致还没能完全达到倒序正确排列。
请帮忙把以往的时间格式统一一下。
具体包括以下：1，统一以2018-01-01 这种日期格式，
                      ,2， 没有具体月份就以2018，不需要加年字。 
                      ,3，同时请把时间字段固定格式，以后导入数据自动调整。

@immo-LinhaiTan  请看原文 附图

**Comment by immo-jianyu** [comment]
![1](https://user-images.githubusercontent.com/34562067/37692243-60ce21d8-2cf2-11e8-8a25-d47566e04bd7.jpg)

**Comment by immo-jianyu** [comment]
![2](https://user-images.githubusercontent.com/34562067/37692291-9b5c0022-2cf2-11e8-93e3-73b5bac594c0.jpg)

**Comment by immo-jianyu** [comment]
已验收，谢谢。
