### ISSUE TITLE
说明书录入 富马酸替诺福韦二吡呋酯片、尼美舒利胶囊（东莞五院提供）

### ISSUE THREAD

**Issue by immo-linziying** [Immortalshealth/HPMS3.0#179]
附件为东莞五院提供的富马酸替诺福韦二吡呋酯片说明书图片，请安排兼职录入。
[富马酸替诺福韦二吡呋酯片.zip](https://github.com/Immortalshealth/HPMS3.0/files/1827815/default.zip)

**Comment by immo-linziying** [comment]
这份是尼美舒利胶囊的说明书
![default](https://user-images.githubusercontent.com/34183265/37697811-ea47b416-2d19-11e8-9032-d718ec9d940c.jpg)

**Comment by immo-jianyu** [comment]
584149dd66a042028fd5247522ba5c32 尼美舒利胶囊
391ede507f114f24a504227e1d9b8dea 富马酸替诺福韦二吡呋酯片
已完成
