### ISSUE TITLE
郁南县人民医院：单个病人的医嘱保存时访问失败无法保存

### ISSUE THREAD

**Issue by lukaidi** [Immortalshealth/HPMS3.0#181]
报错界面见下图
![image](https://user-images.githubusercontent.com/27648997/37746319-9ba33fba-2db4-11e8-82bd-0a7dabd6412a.png)
![image](https://user-images.githubusercontent.com/27648997/37746324-a102e56e-2db4-11e8-8a7e-84fb45c65576.png)

**Comment by immo-hyb** [comment]
@lukaidi 这个报错是药品规则没编译造成的。你在药品目录那里重新编译一下。
