### ISSUE TITLE
郁南县人民医院：门诊科室抗菌药物分析中静脉输液使用率统计不正确

### ISSUE THREAD

**Issue by lukaidi** [Immortalshealth/HPMS3.0#182]
![image](https://user-images.githubusercontent.com/27648997/37746468-4d98bd08-2db5-11e8-818c-24e0d9ca3394.png)

**Comment by lukaidi** [comment]
![image](https://user-images.githubusercontent.com/27648997/37746552-c1b80aae-2db5-11e8-9ae1-63b9cd1bd7fd.png)

**Comment by lukaidi** [comment]
SELECT 
  * 
FROM
  (SELECT 
    o.department,
    o.doc_name,
    SUM(od.amount) amount,
    SUM(IF(p.flag1 > 0, od.amount, 0)) amount1,
    COUNT(DISTINCT o.id) c,
    COUNT(DISTINCT (IF (o.flag1 > 1, o.id, NULL))) c1,
    COUNT(
      DISTINCT CONCAT(pres_date, o.patient_no, NAME)
    ) cc,
    COUNT(
      DISTINCT (
        IF (
          o.flag1 > 1,
          CONCAT(pres_date, o.patient_no, NAME),
          NULL
        )
      )
    ) cc1,
    COUNT(
      DISTINCT (
        IF(
          (SELECT 
            COUNT(0) 
          FROM
            eng_cf_message ecm 
          WHERE ecm.cf_id = o.id 
            AND ecm.TYPE = '静脉用药') > 0,
          o.id,
          NULL
        )
      )
    ) cc2 
  FROM
    eng_cf o 
    LEFT JOIN eng_cf_item od 
      ON o.id = od.cfid 
    LEFT JOIN his_product p 
      ON p.id = od.drug 
  WHERE o.pres_date_time >= ? EcfrqBegin 
    AND o.pres_date_time <= CONCAT(? EcfrqEnd, 'z') 
    AND o.pres_source = ? EpresSource 
    AND o.department = ? Edepartment 
    AND o.doc_name = ? EdocName 
  GROUP BY ? EgroupBy1) zz 
ORDER BY ? Eorderby1 ? EsortOrder

**Comment by lukaidi** [comment]
SQL：
`SELECT 
  * 
FROM
  (SELECT 
    o.department,
    o.doc_name,
    SUM(od.amount) amount,
    SUM(IF(p.flag1 > 0, od.amount, 0)) amount1,
    COUNT(DISTINCT o.id) c,
    COUNT(DISTINCT (IF (o.flag1 > 1, o.id, NULL))) c1,
    COUNT(
      DISTINCT CONCAT(pres_date, o.patient_no, NAME)
    ) cc,
    COUNT(
      DISTINCT (
        IF (
          o.flag1 > 1,
          CONCAT(pres_date, o.patient_no, NAME),
          NULL
        )
      )
    ) cc1,
    COUNT(
      DISTINCT (
        IF(
          (SELECT 
            COUNT(0) 
          FROM
            eng_cf_message ecm 
          WHERE ecm.cf_id = o.id 
            AND ecm.TYPE = '静脉用药') > 0,
          o.id,
          NULL
        )
      )
    ) cc2 
  FROM
    eng_cf o 
    LEFT JOIN eng_cf_item od 
      ON o.id = od.cfid 
    LEFT JOIN his_product p 
      ON p.id = od.drug 
  WHERE o.pres_date_time >= ? EcfrqBegin 
    AND o.pres_date_time <= CONCAT(? EcfrqEnd, 'z') 
    AND o.pres_source = ? EpresSource 
    AND o.department = ? Edepartment 
    AND o.doc_name = ? EdocName 
  GROUP BY ? EgroupBy1) zz 
ORDER BY ? Eorderby1 ? EsortOrder `

**Comment by immo-wsn** [comment]
重新点评之后就好了

**Comment by immo-kirito** [comment]
@immo-wsn    为什么会出现这个问题呢，是否是需要每次都重新点评

**Comment by immo-wsn** [comment]
就是系统有一段时间停了,中间一些数据没有点评所以数据才会不正常。只要系统正常运行是没有这个问题的

**Comment by lukaidi** [comment]
@immo-kirito 二月的数据我手动抽取了一遍，所以我也需要手动点评。
