### ISSUE TITLE
说明书录入 熊去氧胆酸胶囊等6份（兴宁妇幼提供）

### ISSUE THREAD

**Issue by immo-linziying** [Immortalshealth/HPMS3.0#183]
附件为兴宁妇幼提供的6份说明书，请安排兼职录入。
[兴宁妇幼说明书.zip](https://github.com/Immortalshealth/HPMS3.0/files/1835942/default.zip)

**Comment by immo-jianyu** [comment]
已完成。12月已经录入的说明书兴宁妇幼再次给过来更新，证明医院说明书包比较旧，请考虑把我们最近的全包更新过去。
以下为这个六份说明书结果
83e20256b12841ea96086798f77dbf83 熊去氧胆酸片
df443d7326154ddfbb9141efa5e94d66 熊去氧胆酸胶囊
3615c0d7bc334c42b69f3e8e41616cc6 散结乳癖膏
0132ab4d78fe4bc98f63a6abd3a2e405 藿香正气口服液
151303059703259米力农注射液
151393198088630、151393198088627氨甲环酸注射液（两规格）
