### ISSUE TITLE
规则“超适应症”处方评估测试无结果

### ISSUE THREAD

**Issue by immo-lindanxia** [Immortalshealth/HPMS3.0#189]
“超适应症”规则的警示等级为2级；
经查，系统设置已将2级警示开放，但处方评估测试仍无结果显示。
如：葡萄糖酸钙维D2咀嚼片(Ⅱ)、葡萄糖酸钙锌口服溶液等。
![rs08 a7zxjwj x6w b7e](https://user-images.githubusercontent.com/34230763/38065509-40be97f2-3336-11e8-90ef-d8de74546766.png)
系统环境：http://192.168.1.232:9999/hpms/home

**Comment by immo-wsn** [comment]
代码里面,事前的话默认是只保存3级或以上的警示,这个警示级别为2级的话是不会保存的，所以展示的时候就没有了这条2级的警示;

**Comment by immo-wsn** [comment]
现在已经更新上去了,2级的警示也会展示
![image](https://user-images.githubusercontent.com/35050720/38134334-152fc83a-3445-11e8-9e8d-e14ae59361b3.png)

**Comment by immo-kirito** [comment]
@immo-lindanxia   丹霞，测试一下问题解决没有，解决了就关闭一下
