### ISSUE TITLE
姑苏医院项目：社区医院新旧医院名称数据重复项合并

### ISSUE THREAD

**Issue by immo-tanxu** [Immortalshealth/HPMS3.0#191]
姑苏社区医院由于更名，导致新旧社区医院名称在报表都有数据展示，需将重复的合并。
![image](https://user-images.githubusercontent.com/35992093/38067571-c5c48b9c-333f-11e8-814b-503bd67dd8e5.png)

**Comment by immo-fyh** [comment]
这个问题不是已经处理了。 @immo-tanxu

**Comment by immo-fyh** [comment]
如果没有合并的话，请勇兵哥他们帮忙，BI数据是不是从程序代码进行抽取的数据。姑苏的BI不是使用sql脚本抽取数据。 @immo-tanxu @immo-hyb

**Comment by immo-fyh** [comment]
已处理 。 @immo-tanxu
