### ISSUE TITLE
知识库--说明书栏目厂家简称部分显示不出

### ISSUE THREAD

**Issue by immo-jianyu** [Immortalshealth/HPMS3.0#193]
在数据库zsk,sms表里，manufacturer-short(厂家简称字段)有bug，经常为null，同一用户录入统一厂家不同的产品也有部分显示不出厂家简称。直接导致知识库，说明书栏目厂家简称也为空，需要修复。
![2](https://user-images.githubusercontent.com/34562067/38069428-d3c3a81e-3348-11e8-9157-caa31b430653.jpg)
![1](https://user-images.githubusercontent.com/34562067/38069430-d841ae40-3348-11e8-92a4-bd27e26b0e95.jpg)

**Comment by immo-LinhaiTan** [comment]
已修复，原因:入录说明书时候没有把厂家简称传到后台

**Comment by immo-jianyu** [comment]
请把已有的数据manufacturer-short为null的或空的补全，同时刷新到知识库说明书栏目 @immo-hyb

**Comment by immo-kirito** [comment]
@immo-jianyu @immo-hyb 跟进一下问题是否已解决

**Comment by immo-jianyu** [comment]
问题已全部解决。谢谢
