### ISSUE TITLE
新版药品目录测试-DDD值修改时无法选单位

### ISSUE THREAD

**Issue by immo-sitingchen** [Immortalshealth/HPMS3.0#22]
![image](https://user-images.githubusercontent.com/33406481/32473368-e81826e6-c32c-11e7-8c47-4a836913663a.png)

**Comment by immo-hyb** [comment]
这是是业务问题，需要评估是否需要修改ddd值的单位，放开单位修改的话，如果改错了后续强度算不了。这种需要修改ddd单位的数据非常少，可以后台帮处理。个人不建议放开单位修改
