### ISSUE TITLE
新版药品目录测试-门诊/住院单位

### ISSUE THREAD

**Issue by immo-sitingchen** [Immortalshealth/HPMS3.0#23]
1)	下拉无选项
2)	有的药品调不出单位

![image](https://user-images.githubusercontent.com/33406481/32473432-264e788e-c32d-11e7-9eca-5ac61a94a4f8.png)

**Comment by immo-hyb** [comment]
数据问题，这里是没有抽取该药品的门诊、住院单位，所以下拉中没有单位选择。
