### ISSUE TITLE
新版药品目录测试-药品排序无规律

### ISSUE THREAD

**Issue by immo-sitingchen** [Immortalshealth/HPMS3.0#24]
![image](https://user-images.githubusercontent.com/33406481/32473542-90f51f6c-c32d-11e7-9df1-9f51ca80b686.png)

**Comment by immo-duanzhao** [comment]
@immo-hyb

**Comment by immo-hyb** [comment]
这里暂未接到需要药品名称排序的需求。如果有这样的需求可以添加
