### ISSUE TITLE
新版药品目录测试-新增数据有误

### ISSUE THREAD

**Issue by immo-sitingchen** [Immortalshealth/HPMS3.0#29]
为什么新增后的30位没有药品编码？是限定了不能生成30位编码吗？

![image](https://user-images.githubusercontent.com/33406481/32473793-e209d05e-c32e-11e7-8073-229b9f986d69.png)
![image](https://user-images.githubusercontent.com/33406481/32473907-72fa9e4a-c32f-11e7-852b-3245512c9b38.png)

**Comment by immo-hyb** [comment]
医院自己新增的30位目前没有给出编码，没有编码不影响业务逻辑
