### ISSUE TITLE
新版药品目录-抗菌药物分类显示异常

### ISSUE THREAD

**Issue by immo-joyce** [Immortalshealth/HPMS3.0#46]
属于广东省抗菌药物目录内的药品，没有显示正确的抗菌药物分类名称（如氟康唑氯化钠注射液应为抗真菌药）
![1](https://user-images.githubusercontent.com/33405589/32825691-de0ec222-ca20-11e7-93e5-9b026eef1809.png)

**Comment by immo-xxl** [comment]
本地已解决，189出现这种情况可能是数据的问题。


![111](https://user-images.githubusercontent.com/33480803/34476705-1b2358b2-efce-11e7-8d2a-701e4c207641.png)
