### ISSUE TITLE
新版药品目录-药品标准数据异常

### ISSUE THREAD

**Issue by immo-joyce** [Immortalshealth/HPMS3.0#47]
部分药品的标准规格、有效成分的实际值不为0，但数据库显示为0，可能是入库有误
![2](https://user-images.githubusercontent.com/33405589/32825865-61e7df8e-ca21-11e7-8456-5be2111c7bdb.png)

**Comment by immo-hyb** [comment]
@immo-joyce  已经修复，麻烦新凤帮复核下

**Comment by immo-joyce** [comment]
数据库上看这个已经没问题了，注意还要刷新到新药品目录
