### ISSUE TITLE
临床用药检测->用药警示分析->门诊用药警示分析报表->不应该出现乱码

### ISSUE THREAD

**Issue by immo-duanzhao** [Immortalshealth/HPMS3.0#48]
![image](https://user-images.githubusercontent.com/33340384/32936717-5c7d0534-cbb0-11e7-88db-172b9dcd6a7a.png)
测试人： 方俊
测试时间： 2017年 11月14 日

**Comment by immo-hyb** [comment]
没测试到乱码，方俊那边反馈也没有乱码了。
