### ISSUE TITLE
首页-处方评估-右侧案例

### ISSUE THREAD

**Issue by immo-duanzhao** [Immortalshealth/HPMS3.0#54]
点击案例例子除了“药品与药品-注射剂配伍”有结果，其他均显示未发现不合理用药情况。
![image](https://user-images.githubusercontent.com/33340384/33052119-4a1ebd1a-cea8-11e7-9a80-a4c134055e48.png)

**Comment by immo-hyb** [comment]
警示等级设置问题，已经调整。
