### ISSUE TITLE
系统维护-新说明书维护

### ISSUE THREAD

**Issue by immo-duanzhao** [Immortalshealth/HPMS3.0#55]
界面布局混乱，说明书内容全部堆在一起，应该默认初始化格式显示。
![image](https://user-images.githubusercontent.com/33340384/33052154-6e379a3c-cea8-11e7-962f-fd48c2d46b64.png)
测试时间：2017年11月14日
测试人： 邱嘉敏

**Comment by immo-hyb** [comment]
未发现此问题
