### ISSUE TITLE
药学工作站-系统设置

### ISSUE THREAD

**Issue by immo-duanzhao** [Immortalshealth/HPMS3.0#57]
备注中有些只是标记的重复，备注没有起到作用。建议完善备注，包括作用，设置时规定。
![image](https://user-images.githubusercontent.com/33340384/33052247-e7126d24-cea8-11e7-978d-b13073f2a200.png)
测试时间：2017年11月14日
测试人： 邱嘉敏

**Comment by immo-hyb** [comment]
没明白啥意思

**Comment by immo-kirito** [comment]
这个意思就是表示系统配置项里面对于配置的描述不够具体，业务人员看不明白，对于一些特定类型的值没有注明 @immo-hyb

**Comment by immo-hyb** [comment]
已经处理
