### ISSUE TITLE
药学工作站-系统权限-用户/角色管理

### ISSUE THREAD

**Issue by immo-duanzhao** [Immortalshealth/HPMS3.0#58]
系统初始化的角色/用户，建议建立实施版本的用户/角色体系。
![image](https://user-images.githubusercontent.com/33340384/33052278-0b6f52f4-cea9-11e7-9071-778649158187.png)
测试时间：2017年11月14日
测试人： 邱嘉敏

**Comment by immo-hyb** [comment]
已处理。
![image](https://user-images.githubusercontent.com/33407449/33194147-c60eabe4-d108-11e7-9053-248404665164.png)
![image](https://user-images.githubusercontent.com/33407449/33194155-d33ea79c-d108-11e7-8ba1-fb97d49b18f3.png)
