### ISSUE TITLE
药学工作站-系统字典-药品目录

### ISSUE THREAD

**Issue by immo-duanzhao** [Immortalshealth/HPMS3.0#59]
无法比对，报错：[object Object] 
![image](https://user-images.githubusercontent.com/33340384/33052308-32f701b4-cea9-11e7-97c2-85020c134835.png)
页面字段“比对厂家”中显示的是药品规格，页面字段内容混乱。
![image](https://user-images.githubusercontent.com/33340384/33052313-3876db32-cea9-11e7-9c9b-534f0d0aa8b9.png)
	测试时间：2017年11月14日
	测试人： 邱嘉敏
	测试地址：http://192.168.20.209:8080/hpms
	登陆用户： gly 123
	测试模块： 全部
	测试环境：Windows7 64位操作系统、360 9.1版本浏览器

**Comment by immo-hyb** [comment]
哦，这个是旧的药品目录菜单，目前已经不支持了，后续把这个菜单禁止显示吧
