### ISSUE TITLE
首页-新药品目录

### ISSUE THREAD

**Issue by immo-duanzhao** [Immortalshealth/HPMS3.0#61]
	药品目录表头字段排序比较乱，建议将医院关注的指标往前放，容易查找（例如：基药、抗菌药物、DDD值、抗菌药物分类、阳光用药分类、医保、医保编号等字段）
![image](https://user-images.githubusercontent.com/33340384/33052986-6b76f3ac-ceac-11e7-8852-d2541758fedf.png)
	点击抗菌药物查找，分类选“无”，点击后只出现一条数据，该条数据的抗菌药物那显示是“否”
![image](https://user-images.githubusercontent.com/33340384/33052992-76f7c94a-ceac-11e7-9e37-6bbf2dbd5d0d.png)
	点娠用药-全部点击查找，菜单那出现“4、5”这样的表达形式，用鼠标在“4”那点击一下就出现“D”
![image](https://user-images.githubusercontent.com/33340384/33053008-87ddf7de-ceac-11e7-8ee5-1fd3a6a3116a.png)
![image](https://user-images.githubusercontent.com/33340384/33053009-89d66d28-ceac-11e7-8878-a759ff9edddc.png)
	菜单为“空”，不设置“是与否”的话，该条数据不能单独搜索出来，包含“精麻毒放”、“医保”等字段
![image](https://user-images.githubusercontent.com/33340384/33053020-929a1de2-ceac-11e7-94d7-09c951ea8924.png)
	药品比对：点击药品名称进行比对，比对界面关联不到相关药品，有些药品可以，但是
![image](https://user-images.githubusercontent.com/33340384/33053310-d50ce870-cead-11e7-9e95-515c1921fa81.png)
![image](https://user-images.githubusercontent.com/33340384/33053334-ece47364-cead-11e7-8909-434bb83b0d30.png)

**Comment by immo-hyb** [comment]
查询的已经修复。
药品比对那个是数据问题，真是医院环境不会发生。
