### ISSUE TITLE
严重问题A ：门诊抗菌药物使用排名，点击问题截图

### ISSUE THREAD

**Issue by immo-sitingchen** [Immortalshealth/HPMS3.0#64]
门诊抗菌药物使用排名，点击问题截图
![image](https://user-images.githubusercontent.com/33406481/33162559-1775c9c6-d065-11e7-8bf6-0939d49c02df.png)

**Comment by immo-kirito** [comment]
问题是啥啊，问一下曾伟 @immo-sitingchen

**Comment by immo-sitingchen** [comment]
曾伟说他忘记了具体的问题是什么，我让他后面测试了再补充过来。 @immo-kirito
