### ISSUE TITLE
缺陷问题B：模拟处方评估，弹框提示中，点击药品名称，无法弹出药品说明书 

### ISSUE THREAD

**Issue by immo-sitingchen** [Immortalshealth/HPMS3.0#65]
模拟处方评估，弹框提示中，点击药品名称，无法弹出药品说明书 
![image](https://user-images.githubusercontent.com/33406481/33162653-a0067204-d065-11e7-8b39-51c313ef3442.png)

**Comment by immo-xxl** [comment]
问题已解决
