### ISSUE TITLE
严重问题A：药品目录，未比对药品，手工进行最后选取药品的时候，双击选取，出现错误。

### ISSUE THREAD

**Issue by immo-sitingchen** [Immortalshealth/HPMS3.0#66]
药品目录，未比对药品，手工进行最后选取药品的时候，双击选取，出现错误。
![image](https://user-images.githubusercontent.com/33406481/33162746-2adfbade-d066-11e7-881b-0a25f2598abe.png)

**Comment by immo-kirito** [comment]
旧版药品目录不要测试
