### ISSUE TITLE
严重问题A   ： 临床用药监测-临床用药干预-住院警示管理

### ISSUE THREAD

**Issue by immo-sitingchen** [Immortalshealth/HPMS3.0#68]
临床用药监测-临床用药干预-住院警示管理-选取2016.12.30到2016.12.31日的数据，任意点击一种药品的警示信息，点击右侧的：“审”字，显示未发现不合理用药情况。这明明是我们自己提示的不合理用药警示，我什么都没有修改，再审一次，居然提示没有不合理

![image](https://user-images.githubusercontent.com/33406481/33163507-d975a024-d069-11e7-8aab-cd03ea2fa271.png)

**Comment by immo-hyb** [comment]
已处理

**Comment by immo-hyb** [comment]
数据问题，测试数据药品导少了一部分。目前数据已经修改。
