### ISSUE TITLE
药品目录-问题数据展示问题

### ISSUE THREAD

**Issue by immo-duanzhao** [Immortalshealth/HPMS3.0#70]
![image](https://user-images.githubusercontent.com/33340384/33470335-af7ff83e-d6a2-11e7-827d-936f4014c774.png)
**在问题数据中，会出现转换比或门诊单位都没有标红的**
![image](https://user-images.githubusercontent.com/33340384/33470348-c48f50e4-d6a2-11e7-8bc2-52cbaf3a7e50.png)
**根据ID查询某个药品时，转换比或门诊单位才会标红**

测试时间：2017年12月1日
测试地址：http://192.168.20.209:8080/drugCatalog/index.html
登陆用户： gly 123
测试环境：Windows7 64位操作系统、chrome浏览器

**Comment by immo-hyb** [comment]
已修改更新到209
