### ISSUE TITLE
广医三院code_pro编码更新

### ISSUE THREAD

**Issue by immo-linziying** [Immortalshealth/HPMS3.0#74]
广医三院中，以前比对的药品code_pro的编码使用的是旧的19+6编码。
重新比对药品可以将编码替换成19+7，但会将原有的自定义规则清空。
需要研发部提供编码的更新方案。
@immo-kirito 

![_20171204093539](https://user-images.githubusercontent.com/34183265/33532664-83374828-d8d6-11e7-883a-c88ea0325f85.jpg)

**Comment by immo-hyb** [comment]
方案已经跟小莫和子莹说过了。

**Comment by immo-kirito** [comment]
@immo-linziying @imm-mobocheng 这个问题如果解决了请关闭一下
