### ISSUE TITLE
药品说明书录入问题

### ISSUE THREAD

**Issue by immo-eugene** [Immortalshealth/HPMS3.0#82]
@1、选择19+7编码保存后，重新进入修改状态，页面没有显示19+7编码和批准文号
![tim 20171208153649](https://user-images.githubusercontent.com/33345142/33755867-c67c5312-dc2d-11e7-838e-5c7425b8fef4.jpg)

2、目前规格取的是药监规格，录入时会影响编码选择
解决：需要改为选取标准规格
![tim 20171208154036](https://user-images.githubusercontent.com/33345142/33755955-33ce9150-dc2e-11e7-83bd-e33475baa6a3.jpg)

3、目前只显示批准文号，不显示注册证号，不便同品规多个注册证号的编码选择
解决：需要新增一列显示注册证号，或者设定当药品没有批准文号时，显示注册证号
![tim 20171208154711](https://user-images.githubusercontent.com/33345142/33756270-a8c48018-dc2f-11e7-809a-b08983bea1a9.jpg)

@immo-kirito 
@immo-joyce

**Comment by immo-joyce** [comment]
3、有批准文号取批准文号，没有批准文号取注册证号 @immo-hyb
