### ISSUE TITLE
电白区中医院闪退问题

### ISSUE THREAD

**Issue by immoJack** [Immortalshealth/HPMS3.0#84]
医院说使用我们的药事软件会出现闪退。医院信息科的处理方式是重装系统，目前已重装20多台电脑。所以信息科目前都是把药事系统是关闭的。今天（2017.12.11）徐工反映已开药事系统半个多月，今天又有一台电脑出现闪退。我问徐工验收需要解决哪些问题。徐工说首先重装就是大问题，这个问题解决不了，没法验收。我问除了闪退重装，已经重装的电脑是否有其他问题，徐工说没有。
肖总今天（2017.12.11）下达命令，本周内必须解决电白区中医院闪退的问题。请大明协调解决。

**Comment by immo-kirito** [comment]
已经与电脑中医院的徐工沟通过了，不是我们这边的问题，已经提供对应的方案需要去检查his的版本问题
