### ISSUE TITLE
肇庆市一说明书调不出来

### ISSUE THREAD

**Issue by immo-lindanxia** [Immortalshealth/HPMS3.0#90]
肇庆市一部分药品，如艾普拉唑肠溶胶囊、吸入用复方异丙托溴铵溶液、艾地苯醌片等医院环境均可查到说明书数据，且药品目录比对正确，但医生端无法调取到说明书。可能是DLL的问题。
![s fmc_bb6p a bckux9hc t](https://user-images.githubusercontent.com/34230763/34193608-8e9d5214-e58f-11e7-97e9-d9c103d10fd6.png)
![8kajsf7_ 5 v 3i 6li5n](https://user-images.githubusercontent.com/34230763/34193619-9e0f3b0e-e58f-11e7-81e3-a9ba0bb108f8.png)
![7mmq6y 6y4ybs4k t1ymio](https://user-images.githubusercontent.com/34230763/34193645-c882b294-e58f-11e7-9543-677c874aa777.png)

**Comment by immo-xxl** [comment]
唐老师更新了肇庆市一的说明书，查不出来的是该说明书的ID有变化，现在已经更新了此说明书。
