### ISSUE TITLE
药监数据抓取

### ISSUE THREAD

**Issue by immo-joyce** [Immortalshealth/HPMS3.0#97]
自药监系统改版后，药监数据抓取工作难以进行，对标准数据的更新工作带来严重影响（目前MCD中最新的药监数据是2017年2月），希望研发部的同事能找出解决问题的办法。
抓取数据的网址：http://qy1.sfda.gov.cn/datasearch/face3/base.jsp?tableId=36&tableName=TABLE36&title=%E8%BF%9B%E5%8F%A3%E8%8D%AF%E5%93%81&bcId=124356651564146415214424405468
优先抓取数据是“国产药品”和“进口药品”，其他数据如果耗时太长可以不抓取。
药监数据抓取模板请查看钉钉-研发部-文件。
![image](https://user-images.githubusercontent.com/33405589/34337672-51bc3cfa-e99c-11e7-9836-d5f7762192f9.png)

**Comment by immo-jianyu** [comment]
需求不属于药事系统的 已在data上提出同样问题
